create database store;
use store;

create table stores 
(store_id int primary key,
store_name varchar(200) not null,
phone varchar(25),
email varchar(200),
street varchar(200),
city varchar(200),
state varchar(30),
zip_code varchar(30)); 

create table customers
(customer_id int primary key,
first_name varchar(200) not null,
last_name varchar(200),
phone varchar(30),
email varchar(200),
street varchar(200),
city varchar(30),
state varchar(30),
zip_code varchar(30));

create table brands
(brand_id int primary key,
brand_name varchar(200));

create table categories
(category_id int primary key,
category_name varchar(200) not null);

create table products
(product_id int primary key,
product_name varchar(255),
brand_id int not null,
category_id int not null,
model_year int,
list_price decimal(10,2),
foreign key(brand_id) references brands(brand_id),
foreign key(category_id) references categories(category_id));

create table stocks
(store_id int not null,
product_id int not null,
quantity int,
foreign key(store_id) references stores(store_id),
foreign key(product_id) references products(product_id));

create table staffs
(staff_id int primary key,
first_name varchar(50) not null,
last_name varchar(50),
email varchar(200),
phone varchar(30),
`active` int,
store_id int not null,
manager_id int,
foreign key(store_id) references stores(store_id));

create table orders
(order_id int primary key,
customer_id int,
order_status int,
order_date date not null,
required_date date not null,
shipped_date date,
store_id int not null,
staff_id int not null,
foreign key(customer_id) references customers(customer_id),
foreign key(store_id) references stores(store_id),
foreign key(staff_id) references staffs(staff_id));

create table order_items
(order_id int,
item_id int,
product_id int not null,
quntity int,
list_price decimal(10,2),
discount decimal(4,2),
foreign key(order_id) references orders(order_id),
foreign key(product_id) references products(product_id));

select * from brands;
select * from categories;
select * from customers;
select * from stores;
select * from products;
select * from stocks;
select * from staffs;
select * from orders;
select * from order_items;


-- 3.1 Sales Analysis 
-- • Calculate total revenue generated by each store. 
with revenue_cal as
(select s.store_id,s.store_name,((oi.quntity*oi.list_price)-oi.discount) as revenue from order_items as oi
inner join orders as o on oi.order_id = o.order_id
inner join stores as s on s.store_id = o.store_id)
select store_id,store_name, sum(revenue) as total_revenue from  revenue_cal
group by store_name;

-- • Identify top 5 best-selling products. 
select p.product_id,p.product_name,sum(quntity) as total_number_product_sells from order_items as oi
inner join products as p on p.product_id = oi.product_id
group by oi.product_id
order by total_number_product_sells desc
limit 5;

-- • Calculate monthly sales trends to observe seasonality and growth. 
-- select order_date, monthname(order_date) as `month`, count(*) as total_number_product_sell from orders
-- group by `month`;  # this quer gives us the how many number of products order per months
with monthly as
(select monthname(o.order_date) as `month`,((oi.quntity*oi.list_price)-oi.discount) as revenue from order_items as oi
inner join orders as o on oi.order_id = o.order_id)
select `month`, sum(revenue) as total_sale from monthly
group by `month`;

-- • Identify Top-Selling Product per Category 
select ca.category_name,sum(quntity)as total_number_product_sells from order_items as oi
inner join products as p on p.product_id = oi.product_id
inner join categories as ca on ca.category_id = p.category_id
group by ca.category_name
order by total_number_product_sells desc
limit 1;

-- • List of Products with Running Total of Sales 
with sales as
(select p.product_id,p.product_name, ((oi.quntity*oi.list_price)-oi.discount) as revenue from products as p
inner join order_items as oi on oi.product_id = p.product_id
group by p.product_id,p.product_name)
select *,sum(revenue) over(order by product_id) as Running_Total_of_Sales from sales;

-- 3.2 Customer Analysis 
-- • Identify customers with the highest purchases. 
with highest as 
(select c.customer_id,c.first_name,c.last_name,((oi.quntity*oi.list_price)-oi.discount) as total_purchases from order_items as oi
inner join orders as o on o.order_id =oi.order_id
inner join customers as c on c.customer_id = o.customer_id
group by c.customer_id,c.first_name,c.last_name)
select * from highest
order by total_purchases desc
limit 1;

-- • Find customers who have not placed any orders. 
select * from customers as c
left join orders as o on o.customer_id = c.customer_id
where o.customer_id is null ;  
# there is no customer which not placed any order 

-- • Identify customers who have placed at least 3 orders and spent more than $ 25,000. 
with highest as 
(select c.customer_id,c.first_name,c.last_name,count(*) as nos_of_orders,((oi.quntity*oi.list_price)-oi.discount) as total_purchases from order_items as oi
inner join orders as o on o.order_id =oi.order_id
inner join customers as c on c.customer_id = o.customer_id
group by c.customer_id,c.first_name,c.last_name)
select * from highest
where nos_of_orders>=3 and total_purchases > 25000;

-- 3.3 Inventory Management 
-- • Identify low-stock products (below 50 items in inventory). 
with  low_stock as 
(select p.product_id,p.product_name , sum(quantity) as stock from products as p
inner join stocks as s on s.product_id = p.product_id
group by p.product_id,p.product_name)
select * from low_stock 
where stock < 50;

-- 3.4 Employee Performance Analysis 
-- • Identify the top 5 employees based on order transactions handled. 
with top as
(select st.staff_id,st.first_name,st.last_name, count(*) as no_order_handled from orders as o
inner join staffs as st on st.staff_id = o.staff_id
group by  st.staff_id,st.first_name,st.last_name)
select * from top
order by no_order_handled desc
limit 5;

-- • Identify staff members with the highest number of orders processed. 
with op as 
(select st.staff_id,st.first_name,st.email,count(*) as no_orders_processed from staffs as st
inner join orders as o on st.staff_id = o.staff_id
where shipped_date is not null
group by st.staff_id,st.first_name,st.email)
select * from op
order by no_orders_processed desc
limit 1;

-- • Rank Staff Based on Revenue Generated 
with rankk as
(select st.staff_id,st.first_name, st.email,((oi.quntity*oi.list_price)-oi.discount) as revenue from  staffs as st
left join orders as o on st.staff_id = o.staff_id
left join order_items as oi on o.order_id = oi.order_id)
select *,sum(revenue) total_revenue,dense_rank() over(order by revenue desc) as rankk from rankk
group by st.staff_id,st.first_name, st.email;

-- 3.5 Advanced Reporting 
-- • Rank products by sales volume. 
with rankP as
(select p.product_id,p.product_name,sum(oi.quntity) as total_quntity from products as p
left join order_items as oi on oi.product_id = p.product_id
group by p.product_id,p.product_name)
select *, dense_rank() over(order by total_quntity desc) as pro_rank from rankP;

-- • Compare Monthly Sales with Previous Month. 
with compare as
(with group_month as
(select monthname(order_date) as `Month`,((oi.quntity*oi.list_price)-oi.discount) as sale  from orders as o
inner join order_items as oi on oi.order_id = o.order_id)
select `Month`, sum(sale) as Total_sale from group_month
group by `Month`)
select *, (Total_sale-lag(Total_sale) over()) as sale_compare_to_pre_Month from compare;


-- • Assign Row Number to Orders by Each Customer. 
select c.customer_id,c.first_name,c.last_name,o.order_id, row_number() over(partition by c.customer_id)as order_number from customers as c
inner join orders as o on c.customer_id = o.customer_id;

